version: 0.0
os: linux 
files:
  - source: /
    destination: /opt/app/sapphire
permissions:
  - object: /opt/app/sapphire
    pattern: "*"
    owner: ubuntu
    group: ubuntu 
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  # AfterInstall:
  #   - location: scripts/after_install.sh
  #     timeout: 120
  #     runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 120
      runas: root