version: '3'
services:
  vault:
    tty: yes
    container_name: vault
    cap_add:
      - IPC_LOCK
    volumes:
      - "$LOGDIR:/vault/logs"
      - "$LOCAL_STORAGE:/keys"
      - "$LOCAL_STORAGE/certs:/certs"
    build: ./vault
    ports:
      - "8200:8200/tcp"